version: '3.8'

services:
  db:
    container_name: 'db_c'
    image: postgres:14.2
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
  dec:
    container_name: 'dec_c'
    image: 'dec:1.0'
    depends_on:
      - db
    build: ./src
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./files:/files
    command: bash -c 'sleep 20; python3 upload_to_db.py && uvicorn services:router --host 0.0.0.0 --reload --port 8000'
